version: '3.8'

networks:
  custom_network:
    driver: bridge

services:
  php-apache:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: my_database
    networks:
      - custom_network
    volumes:
      - ./src:/var/www/html
      
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    volumes:
      - mysql-data:/var/lib/mysql   
    networks:
      - custom_network
      
volumes:
  mysql-data:

